name: finanzas_personales
description: Aplicacion movil demo offline para control financiero personal.
publish_to: "none"
version: 0.1.4+5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/Logo_app.png"
  adaptive_icon_background: "#F6FBFF"
  adaptive_icon_foreground: "assets/icon/Logo_app.png"
